"""Custos Storage Provider Layer.

See `design/components/storage-provider-layer/design.md` for the full contract.
"""

from importlib.metadata import PackageNotFoundError, version

from custos_spl.errors import (
    ArtifactNotFound,
    BackendUnavailable,
    ConflictDigest,
    ImmutableViolation,
    InvalidTransactionHandle,
    LeaseBusy,
    LeaseExpired,
    MigrationRequired,
    NotReserved,
    QueryUnsupported,
    SPLError,
    WorkspaceMismatch,
)
from custos_spl.ids import (
    ActivityTypeId,
    ArtifactId,
    ConnectorInstanceId,
    ConnectorTypeId,
    PrincipalId,
    RunId,
    StepId,
    SubscriptionId,
    TenantId,
    WorkflowId,
    WorkflowTemplateId,
    WorkspaceId,
)
from custos_spl.interfaces import (
    ActivityTypeVersion,
    ArtifactDescriptor,
    ArtifactStoreProvider,
    ArtifactUse,
    AuditEvent,
    AuditFilter,
    AuditOutboxBatch,
    AuditOutboxRow,
    CatalogStoreProvider,
    ConnectorCursor,
    ConnectorTypeVersion,
    DedupDuplicate,
    DedupKey,
    DedupReserved,
    DefinitionListFilter,
    DefinitionStoreProvider,
    DeviceCodeSession,
    ExistingCompleted,
    ExistingInFlight,
    IdempotencyRecord,
    IdemReserved,
    KeyReuse,
    LeaseHandle,
    MetadataStoreProvider,
    NotifyEvent,
    PutDedupKeyResult,
    ReserveIdempotencyResult,
    ResumeSubscription,
    Run,
    RunFilter,
    Schedule,
    Step,
    StepAttempt,
    Subscription,
    SubscriptionSelector,
    TransactionHandle,
    WorkflowTemplateVersion,
    WorkflowVersion,
)
from custos_spl.pagination import Cursor, Page

try:
    __version__ = version("custos_spl")
except PackageNotFoundError:
    __version__ = "0+unknown"

__all__ = [
    "ActivityTypeId",
    "ActivityTypeVersion",
    "ArtifactDescriptor",
    "ArtifactId",
    "ArtifactNotFound",
    "ArtifactStoreProvider",
    "ArtifactUse",
    "AuditEvent",
    "AuditFilter",
    "AuditOutboxBatch",
    "AuditOutboxRow",
    "BackendUnavailable",
    "CatalogStoreProvider",
    "ConflictDigest",
    "ConnectorCursor",
    "ConnectorInstanceId",
    "ConnectorTypeId",
    "ConnectorTypeVersion",
    "Cursor",
    "DedupDuplicate",
    "DedupKey",
    "DedupReserved",
    "DefinitionListFilter",
    "DefinitionStoreProvider",
    "DeviceCodeSession",
    "ExistingCompleted",
    "ExistingInFlight",
    "IdemReserved",
    "IdempotencyRecord",
    "ImmutableViolation",
    "InvalidTransactionHandle",
    "KeyReuse",
    "LeaseBusy",
    "LeaseExpired",
    "LeaseHandle",
    "MetadataStoreProvider",
    "MigrationRequired",
    "NotReserved",
    "NotifyEvent",
    "Page",
    "PrincipalId",
    "PutDedupKeyResult",
    "QueryUnsupported",
    "ReserveIdempotencyResult",
    "ResumeSubscription",
    "Run",
    "RunFilter",
    "RunId",
    "SPLError",
    "Schedule",
    "Step",
    "StepAttempt",
    "StepId",
    "Subscription",
    "SubscriptionId",
    "SubscriptionSelector",
    "TenantId",
    "TransactionHandle",
    "WorkflowId",
    "WorkflowTemplateId",
    "WorkflowTemplateVersion",
    "WorkflowVersion",
    "WorkspaceId",
    "WorkspaceMismatch",
    "__version__",
]
