"""Pydantic request/response schemas for the Phase C HTTP surface.

These are pure wire-format models — they describe what bytes go on the
network and nothing else. SPL dataclasses (:class:`custos_spl.Tenant`,
:class:`custos_spl.Workspace`, the :data:`Principal` union, …) stay the
single source of truth for the persisted shape; this module ships the
projection functions (:func:`tenant_to_response`, etc.) that map them
to the wire envelope.

Field-name conventions:

* All API timestamps are ISO-8601 UTC strings rendered via
  :class:`datetime.datetime` → Pydantic's default serializer.
* ``tenant_id`` / ``workspace_id`` / ``principal_id`` are canonical
  opaque-string identifiers used by auth-service. For Phase C create
  requests, these IDs are operator-supplied rather than generated by
  the service.
* ``display_name`` is the human-readable label; it is freely mutable
  through future PATCH endpoints (out of scope for Phase C).
* ``kind`` discriminates the :class:`PrincipalResponse` union exactly
  the way :class:`custos_spl.User` / :class:`custos_spl.ServiceAccount`
  discriminate the persisted union.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from custos_spl.interfaces.auth_store import (
    Principal,
    ServiceAccount,
    Tenant,
    User,
    Workspace,
)
from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Tenant
# ---------------------------------------------------------------------------


class TenantCreateRequest(BaseModel):
    """Body of ``POST /v1/tenants``.

    ``tenant_id`` is operator-supplied (it must be a stable opaque
    string the operator picks for the customer; auth-service does not
    generate it). ``display_name`` is the human-readable label.
    """

    model_config = ConfigDict(extra="forbid")

    tenant_id: Annotated[str, Field(min_length=1, max_length=120)]
    display_name: Annotated[str, Field(min_length=1, max_length=200)]


class TenantResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    tenant_id: str
    display_name: str
    disabled_at: datetime | None
    created_at: datetime


class TenantListResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    tenants: list[TenantResponse]


def tenant_to_response(tenant: Tenant) -> TenantResponse:
    return TenantResponse(
        tenant_id=str(tenant.tenant_id),
        display_name=tenant.display_name,
        disabled_at=tenant.disabled_at,
        created_at=tenant.created_at,
    )


# ---------------------------------------------------------------------------
# Workspace
# ---------------------------------------------------------------------------


class WorkspaceCreateRequest(BaseModel):
    """Body of ``POST /v1/tenants/{tenant_id}/workspaces``.

    ``workspace_id`` is operator-supplied for parity with tenant
    creation. ``tenant_id`` comes from the path, not the body.
    """

    model_config = ConfigDict(extra="forbid")

    workspace_id: Annotated[str, Field(min_length=1, max_length=120)]
    display_name: Annotated[str, Field(min_length=1, max_length=200)]


class WorkspaceResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    workspace_id: str
    tenant_id: str
    display_name: str
    disabled_at: datetime | None
    created_at: datetime


class WorkspaceListResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    workspaces: list[WorkspaceResponse]


def workspace_to_response(workspace: Workspace) -> WorkspaceResponse:
    return WorkspaceResponse(
        workspace_id=str(workspace.workspace_id),
        tenant_id=str(workspace.tenant_id),
        display_name=workspace.display_name,
        disabled_at=workspace.disabled_at,
        created_at=workspace.created_at,
    )


# ---------------------------------------------------------------------------
# Principal (User + ServiceAccount)
# ---------------------------------------------------------------------------


class UserResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: Literal["user"] = "user"
    principal_id: str
    tenant_id: str
    display_name: str
    email: str | None
    disabled_at: datetime | None
    disabled_reason: str | None
    created_at: datetime


class ServiceAccountResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: Literal["serviceAccount"] = "serviceAccount"
    principal_id: str
    workspace_id: str
    display_name: str
    disabled_at: datetime | None
    disabled_reason: str | None
    created_at: datetime


PrincipalResponse = UserResponse | ServiceAccountResponse


def principal_to_response(principal: Principal) -> PrincipalResponse:
    """Project a SPL :data:`Principal` to its wire-format envelope.

    The discriminator is the persisted ``kind`` literal; the projection
    is a straight field-for-field copy with opaque IDs widened to
    plain strings for JSON serialisation.
    """
    if isinstance(principal, User):
        return UserResponse(
            principal_id=str(principal.principal_id),
            tenant_id=str(principal.tenant_id),
            display_name=principal.display_name,
            email=principal.email,
            disabled_at=principal.disabled_at,
            disabled_reason=principal.disabled_reason,
            created_at=principal.created_at,
        )
    assert isinstance(principal, ServiceAccount)
    return ServiceAccountResponse(
        principal_id=str(principal.principal_id),
        workspace_id=str(principal.workspace_id),
        display_name=principal.display_name,
        disabled_at=principal.disabled_at,
        disabled_reason=principal.disabled_reason,
        created_at=principal.created_at,
    )


# ---------------------------------------------------------------------------
# Service-account create
# ---------------------------------------------------------------------------


class ServiceAccountCreateRequest(BaseModel):
    """Body of ``POST /v1/service-accounts``.

    The service account is created in the caller's *current workspace*
    — pulled from the call-context — so the body does not carry a
    workspace id. ``principal_id`` is operator-supplied.
    """

    model_config = ConfigDict(extra="forbid")

    principal_id: Annotated[str, Field(min_length=1, max_length=120)]
    display_name: Annotated[str, Field(min_length=1, max_length=200)]


class PrincipalDisableRequest(BaseModel):
    """Body of ``POST /v1/principals/{principal_id}/disable``."""

    model_config = ConfigDict(extra="forbid")

    reason: Annotated[str, Field(min_length=1, max_length=500)]


# ---------------------------------------------------------------------------
# Permission registry (Phase D / AS-IMPL-009)
# ---------------------------------------------------------------------------


class PermissionResponse(BaseModel):
    """One row in the ``GET /v1/permissions`` response.

    ``declared_by`` carries the loader-side multi-declarer attribution
    (pipe-delimited list of owning components — see
    :mod:`custos_auth.permission_registry`).
    """

    model_config = ConfigDict(extra="forbid")

    name: str
    description: str
    declared_by: str


class PermissionListResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    permissions: list[PermissionResponse]


# ---------------------------------------------------------------------------
# Roles (Phase D / AS-IMPL-009)
# ---------------------------------------------------------------------------


class RoleResponse(BaseModel):
    """One row in the ``GET /v1/roles`` response.

    Mirrors the SPL :class:`Role` dataclass plus the built-in scope-rule
    metadata so clients can render the role catalogue without a
    second round-trip.
    """

    model_config = ConfigDict(extra="forbid")

    role_id: str
    name: str
    description: str
    permission_names: list[str]
    allowed_scopes: list[Literal["workspace", "tenant", "platform"]]


class RoleListResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    roles: list[RoleResponse]


# ---------------------------------------------------------------------------
# Role bindings (Phase D / AS-IMPL-010)
# ---------------------------------------------------------------------------


class RoleBindingCreateRequest(BaseModel):
    """Body of ``POST /v1/workspaces/{workspace_id}/role-bindings``.

    The binding scope is implicit in the path (a workspace endpoint
    binds at :class:`WorkspaceScope` only); ``binding_id`` is server-
    generated so the body carries just the assignment.
    """

    model_config = ConfigDict(extra="forbid")

    principal_id: Annotated[str, Field(min_length=1, max_length=120)]
    role_id: Annotated[str, Field(min_length=1, max_length=120)]


class RoleBindingResponse(BaseModel):
    """Wire envelope for a single :class:`RoleBinding` row.

    ``scope_kind`` is the canonical
    ``"workspace" | "tenant" | "platform"`` tag; ``scope_id`` carries
    the workspace or tenant identifier (or ``None`` for platform-
    scope bindings) so clients can disambiguate without parsing the
    discriminated union.
    """

    model_config = ConfigDict(extra="forbid")

    binding_id: str
    principal_id: str
    role_id: str
    scope_kind: Literal["workspace", "tenant", "platform"]
    scope_id: str | None
    bound_at: datetime
    bound_by: str


class RoleBindingListResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    bindings: list[RoleBindingResponse]


__all__ = [
    "PermissionListResponse",
    "PermissionResponse",
    "PrincipalDisableRequest",
    "PrincipalResponse",
    "RoleBindingCreateRequest",
    "RoleBindingListResponse",
    "RoleBindingResponse",
    "RoleListResponse",
    "RoleResponse",
    "ServiceAccountCreateRequest",
    "ServiceAccountResponse",
    "TenantCreateRequest",
    "TenantListResponse",
    "TenantResponse",
    "UserResponse",
    "WorkspaceCreateRequest",
    "WorkspaceListResponse",
    "WorkspaceResponse",
    "principal_to_response",
    "tenant_to_response",
    "workspace_to_response",
]
