"""Provider interface contracts.

Populated by:
- SPL-003 — DefinitionStoreProvider + CatalogStoreProvider
- SPL-004 — MetadataStoreProvider (full surface)
- SPL-005 — ArtifactStoreProvider
- SPL-006 — AuthStoreProvider
- SPL-007 — LogQueryProvider + MetricsQueryProvider
"""

from custos_spl.interfaces.artifact_store import (
    ArtifactDescriptor,
    ArtifactStoreProvider,
)
from custos_spl.interfaces.auth_store import (
    AuthStoreProvider,
    GlobalScope,
    OidcIdentity,
    Permission,
    Principal,
    PrincipalFilter,
    Role,
    RoleBinding,
    RoleBindingFilter,
    RoleBindingScope,
    ServiceAccount,
    ServiceToken,
    Tenant,
    TenantFilter,
    TenantScope,
    User,
    Workspace,
    WorkspaceFilter,
    WorkspaceScope,
)
from custos_spl.interfaces.catalog_store import (
    ActivityTypeVersion,
    CatalogStoreProvider,
    ConnectorTypeVersion,
)
from custos_spl.interfaces.definition_store import (
    DefinitionListFilter,
    DefinitionStoreProvider,
    WorkflowTemplateVersion,
    WorkflowVersion,
)
from custos_spl.interfaces.metadata_store import (
    ArtifactUse,
    AuditEvent,
    AuditFilter,
    AuditOutboxBatch,
    AuditOutboxRow,
    ConnectorCursor,
    DedupDuplicate,
    DedupKey,
    DedupReserved,
    DeviceCodeSession,
    ExistingCompleted,
    ExistingInFlight,
    IdempotencyRecord,
    IdemReserved,
    KeyReuse,
    LeaseHandle,
    MetadataStoreProvider,
    NotifyEvent,
    PutDedupKeyResult,
    ReserveIdempotencyResult,
    ResumeSubscription,
    Run,
    RunFilter,
    Schedule,
    Step,
    StepAttempt,
    Subscription,
    SubscriptionSelector,
    TransactionHandle,
)

__all__ = [
    "ActivityTypeVersion",
    "ArtifactDescriptor",
    "ArtifactStoreProvider",
    "ArtifactUse",
    "AuditEvent",
    "AuditFilter",
    "AuditOutboxBatch",
    "AuditOutboxRow",
    "AuthStoreProvider",
    "CatalogStoreProvider",
    "ConnectorCursor",
    "ConnectorTypeVersion",
    "DedupDuplicate",
    "DedupKey",
    "DedupReserved",
    "DefinitionListFilter",
    "DefinitionStoreProvider",
    "DeviceCodeSession",
    "ExistingCompleted",
    "ExistingInFlight",
    "GlobalScope",
    "IdemReserved",
    "IdempotencyRecord",
    "KeyReuse",
    "LeaseHandle",
    "MetadataStoreProvider",
    "NotifyEvent",
    "OidcIdentity",
    "Permission",
    "Principal",
    "PrincipalFilter",
    "PutDedupKeyResult",
    "ReserveIdempotencyResult",
    "ResumeSubscription",
    "Role",
    "RoleBinding",
    "RoleBindingFilter",
    "RoleBindingScope",
    "Run",
    "RunFilter",
    "Schedule",
    "ServiceAccount",
    "ServiceToken",
    "Step",
    "StepAttempt",
    "Subscription",
    "SubscriptionSelector",
    "Tenant",
    "TenantFilter",
    "TenantScope",
    "TransactionHandle",
    "User",
    "WorkflowTemplateVersion",
    "WorkflowVersion",
    "Workspace",
    "WorkspaceFilter",
    "WorkspaceScope",
]
