apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStoreName }}
spec:
  provider:
    {{- if eq .Values.provider "vault" }}
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMountPath | quote }}
          role: {{ .Values.vault.authRole | quote }}
    {{- else if eq .Values.provider "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | quote }}
    {{- else if eq .Values.provider "azure" }}
    azurekv:
      vaultUrl: {{ .Values.azure.vaultUrl | quote }}
      authType: WorkloadIdentity
    {{- else if eq .Values.provider "gcp" }}
    gcpsm:
      projectID: {{ .Values.gcp.projectID | quote }}
    {{- end }}
