{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "svc.fullname" . }}
  labels:
    {{- include "svc.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "svc.fullname" . }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
