"""Drift test: Tier 1 JSON sidecar MUST mirror ``capabilities.md``.

The human-curated source of truth is
``design/architecture/capabilities.md``. The Connector Service ships a
JSON sidecar at
``custos_connector/manifest/_data/capability_registry.v1.json`` that the
validator loads at runtime via :mod:`importlib.resources`.

This test parses the markdown, extracts the registered Tier 1 tokens
from each ``### <prefix>.*`` sub-section, and asserts the JSON sidecar
agrees. The two MUST drift together; the JSON is regenerated by hand
when a new token lands in the markdown registry, and a forgotten
regeneration is what this test catches.
"""

from __future__ import annotations

import re
from pathlib import Path

from custos_connector.manifest.capabilities import (
    FORBIDDEN_IN_CAPABILITIES,
    TIER1_RESERVED_PREFIXES,
    TIER1_TOKENS,
)

REPO_ROOT = Path(__file__).resolve().parents[4]
CAPABILITIES_MD = REPO_ROOT / "design" / "architecture" / "capabilities.md"

# A Tier 1 sub-section heading looks like ``### `oci.*` `` (literal
# backticks around the prefix). We capture the prefix from the heading
# and then walk the subsequent table rows until we hit the next
# ``###``-level heading.
_SECTION_RE = re.compile(r"^###\s+`([a-z][a-z0-9-]*)\.\*`\s*$")

# Table rows look like ``| token | meaning |``. We only care about the
# first cell. Skip the header row (``| Token | Meaning |``) and the
# divider row (``|---|---|``) by requiring the first cell to start with
# a lowercase letter — both header and divider fail that test.
_TABLE_ROW_RE = re.compile(r"^\|\s*`?([a-z][a-z0-9.-]+)`?\s*\|")


def _parse_markdown_registry() -> dict[str, set[str]]:
    """Return ``{prefix: {tokens}}`` extracted from the markdown registry."""
    sections: dict[str, set[str]] = {}
    current_prefix: str | None = None
    for raw_line in CAPABILITIES_MD.read_text(encoding="utf-8").splitlines():
        section_match = _SECTION_RE.match(raw_line)
        if section_match is not None:
            current_prefix = section_match.group(1)
            sections.setdefault(current_prefix, set())
            continue
        # Any other ``###`` heading closes the current section.
        if raw_line.startswith("### ") and current_prefix is not None:
            current_prefix = None
        if current_prefix is None:
            continue
        row_match = _TABLE_ROW_RE.match(raw_line)
        if row_match is None:
            continue
        token = row_match.group(1)
        sections[current_prefix].add(token)
    return sections


def test_json_sidecar_matches_markdown_registry() -> None:
    """Every markdown-registered token MUST appear in :data:`TIER1_TOKENS`."""
    sections = _parse_markdown_registry()
    expected: set[str] = set()
    for tokens in sections.values():
        expected.update(tokens)

    missing_from_json = expected - TIER1_TOKENS
    extra_in_json = TIER1_TOKENS - expected
    assert not missing_from_json, (
        f"capability_registry.v1.json is missing tokens that are in "
        f"design/architecture/capabilities.md: {sorted(missing_from_json)}"
    )
    assert not extra_in_json, (
        f"capability_registry.v1.json has tokens that are NOT in "
        f"design/architecture/capabilities.md: {sorted(extra_in_json)}"
    )


def test_reserved_prefixes_match_markdown() -> None:
    """The reserved-prefix set MUST mirror the ``## Reserved Core Prefixes`` table."""
    text = CAPABILITIES_MD.read_text(encoding="utf-8")
    # Each row in the Reserved Core Prefixes table looks like
    # ``| `oci.*` | OCI registries — image and artifact data-plane |``.
    expected = set(re.findall(r"\|\s*`([a-z][a-z0-9-]*)\.\*`\s*\|", text))
    # The markdown table appears twice (once in the Reserved Core
    # Prefixes section, once as ``### <prefix>.*`` sub-section headings
    # which our regex would also match if not bound to ``###``); the
    # ``re.findall`` above is unanchored so it also picks up tokens
    # inside backticks. That overlap is harmless because all sub-section
    # prefixes are also in the Reserved table.
    assert expected == TIER1_RESERVED_PREFIXES, (
        f"sidecar reservedPrefixes={sorted(TIER1_RESERVED_PREFIXES)} disagrees "
        f"with markdown table={sorted(expected)}"
    )


def test_event_remains_forbidden_in_capabilities() -> None:
    """The markdown explicitly forbids ``event.*`` in capabilities."""
    text = CAPABILITIES_MD.read_text(encoding="utf-8")
    assert "MUST NOT appear in `capabilities`" in text
    assert {"event"} == FORBIDDEN_IN_CAPABILITIES
