apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: custos
  labels:
    app.kubernetes.io/name: custos-postgres
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.imageName | quote }}
  bootstrap:
    initdb:
      database: {{ .Values.database }}
      owner: custos
  storage:
    size: {{ .Values.storageSize }}
    {{- if .Values.storageClass }}
    storageClass: {{ .Values.storageClass | quote }}
    {{- end }}
  {{- if .Values.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.backup.destinationPath | quote }}
      endpointURL: {{ .Values.backup.endpointURL | quote }}
      s3Credentials:
        accessKeyId:
          name: custos-minio
          key: accessKey
        secretAccessKey:
          name: custos-minio
          key: secretKey
    retentionPolicy: "30d"
  {{- end }}
